site_name: Wood Badge Songs
pages:
- Home: index.md
- Scout creeds: creeds.md
- Patriotic songs: patriotic.md
- Wood Badge songs: woodbadge.md
- Scout songs: scout.md
- Fun songs: fun.md
- Flag ceremonies: flags.md
- Commands: commands.md

theme: readthedocs
